### ISSUE TITLE
[1.16.4] Crash to desktop & server crash when anything from Iron Furnaces is placed / used.

### ISSUE THREAD

**Issue by Gbergz** [Qelifern/IronFurnaces#29] opened 2021-01-13 09:35 UTC
**Describe the bug**
Crash to desktop & server crash when anything from Iron Furnaces is in proximity to the player.

**To Reproduce**
1. Be close to anything from Iron Furnaces.
2. Server Crashes.
3. Client Crashes.
4. Poof.

**Expected behavior**
That no crash happens.

**Versions**
- **Iron Furnaces**: 2.5.7
- **Forge**: 35.1.36

**Crash-Report**
https://hatebin.com/hcsgmnbked

**Modlist** (Scroll down!)
https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3166753

**Additional Info**
Looks like its a cross mod issue with Refined Storage + Performant for some weird reason? Or maybe thats false info, I don't know.

**Comment by Qelifern** [comment] 2021-01-13 14:30
I downloaded the modpack and started a local server and I was unable to reproduce the error, however. If you updated from an older version of the modpack/ironfurnaces try and solve this by going into your mods folder and deleting ironfurnaces. Then launch your server and after it has finished loading, write stop to save world.
Then put ironfurnaces back into the mods folder and start your server. Then break and replace any furnaces and it should work.
Note: furnace config syncing doesnt work on ironfurnaces-1.16.4-2.5.7 when playing on a server; version 2.5.8 will fix this.

**Comment by Gbergz** [comment] 2021-01-13 14:51
This is exactly what I did, I removed the mod, started the server. Saved the game. Stopped and re-added then started. It worked But as soon as someone places something from IronFurnaces it starts happening again. Same crash as posted above.

**Comment by Qelifern** [comment] 2021-01-13 14:58
From which version did you update from?

**Comment by Gbergz** [comment] 2021-01-13 15:38
2.5.6 this version. https://www.curseforge.com/minecraft/mc-mods/iron-furnaces/files/3152441

**Comment by Qelifern** [comment] 2021-01-13 16:19
Testing updating from 1.8.4 to 1.8.5a with furnaces placed and I did not get a crash. Try removing Perfomant and Ironfurnaces and it might work.

**Comment by Gbergz** [comment] 2021-01-15 21:13
Yeah that didn't work either. Still crashing.

**Comment by XenoMustache** [comment] 2021-02-20 21:51
Unable to recreate issue, closing due to staleness.

**Closed as completed by XenoMustache** 2021-02-20 21:51 UTC
Labels: bug
