### ISSUE TITLE
Crash org/apache/commons/compress/utils/Lists

### ISSUE THREAD

**Issue by nawtr0** [Qelifern/IronFurnaces#158] opened 2023-04-26 03:40 UTC
### Forge Version

1.18.2

### Iron Furnaces Version

13.2.11

### Describe your issue

https://mcpaste.io/c5ec44547259839a
chatgpt:
This is a Minecraft crash report. It appears to be related to an issue with the Iron Furnaces mod. Specifically, the error message mentions a missing class definition for org/apache/commons/compress/utils/Lists. It's possible that this mod requires another mod or library to be installed in order to function properly. You may want to check the Iron Furnaces mod page or consult with the mod developer to see if there are any dependencies that need to be installed. Alternatively, you could try removing the mod and seeing if the crash still occurs.
how to fix it?

**Comment by UnRealDinnerbone** [comment] 2023-05-23 13:23
Any update on this issue? We have multiple reports of people crashing with this in Stoneblock 3

**Comment by nawtr0** [comment] 2023-05-23 16:56
> Any update on this issue? We have multiple reports of people crashing with this in Stoneblock 3

i found that the cause of the problem is redstone when u try to change it specially in rainbow Furnace it causes the crash

**Comment by Shybella** [comment] 2023-05-31 23:52
> Any update on this issue? We have multiple reports of people crashing with this in Stoneblock 3

Still happening, I had to disable the iron furnace mod.

**Comment by TigerWalts** [comment] 2023-07-24 20:04
Duplicate of https://github.com/Qelifern/IronFurnaces/issues/148

`commons-compress` is installed with Forge on the client but not on dedicated servers.

**Closed as completed** 2024-03-05 11:52 UTC
Labels: bug
